config/routes.rb
Rails.application.routes.draw do
  resources :stamps
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :user
  validates :description, presence: true
  validates :value, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  has_many :stamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: %i[ show edit update destroy ]

  def index
    @stamps = Stamp.all
  end

  def show
  end

  def new
    @stamp = Stamp.new
  end

  def edit
  end

  def create
    @stamp = Stamp.new(stamp_params)

    respond_to do |format|
      if @stamp.save
        format.html { redirect_to stamp_url(@stamp), notice: "Stamp was successfully created." }
        format.json { render :show, status: :created, location: @stamp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stamp.update(stamp_params)
        format.html { redirect_to stamp_url(@stamp), notice: "Stamp was successfully updated." }
        format.json { render :show, status: :ok, location: @stamp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stamp.destroy

    respond_to do |format|
      format.html { redirect_to stamps_url, notice: "Stamp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_stamp
      @stamp = Stamp.find(params[:id])
    end

    def stamp_params
      params.require(:stamp).permit(:description, :value, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @stamps = @user.stamps
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carimbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stamps/_form.html.erb
<%= form_with(model: stamp) do |form| %>
  <% if stamp.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stamp.errors.count, "error") %> prohibited this stamp from being saved:</h2>

      <ul>
        <% stamp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stamps/_stamp.html.erb
<div id="<%= dom_id stamp %>">
  <p>
    <strong>Description:</strong>
    <%= stamp.description %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= stamp.value %>
  </p>

</div>

app/views/stamps/edit.html.erb
<h1>Editing stamp</h1>

<%= render "form", stamp: @stamp %>

<br>

<div>
  <%= link_to "Show this stamp", @stamp %> |
  <%= link_to "Back to stamps", stamps_path %>
</div>

app/views/stamps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stamps</h1>

<div id="stamps">
  <% @stamps.each do |stamp| %>
    <%= render stamp %>
    <p>
      <%= link_to "Show this stamp", stamp %>
    </p>
  <% end %>
</div>

<%= link_to "New stamp", new_stamp_path %>

app/views/stamps/new.html.erb
<h1>New stamp</h1>

<%= render "form", stamp: @stamp %>

<br>

<div>
  <%= link_to "Back to stamps", stamps_path %>
</div>

app/views/stamps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stamp %>

<div>
  <%= link_to "Edit this stamp", edit_stamp_path(@stamp) %> |
  <%= link_to "Back to stamps", stamps_path %>

  <%= button_to "Destroy this stamp", @stamp, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="text-red">
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Carimbos:</strong>
    <%= user.stamps.count %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
<%= link_to "Add new stamp", new_stamp_path%>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <h2>Carimbos</h2>
  <ul>
    <% @stamps.each do |stamp| %>
      <p class="text-2xl underline">1x <%= stamp.description %></p>
    <% end %>
  </ul>
</div>
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>